export const emails = [
    {
      id: 'e101',
      createdAt: 1551133930500,
      subject: 'Miss you!',
      body: 'A book is a medium for recording information in the form of writing or images. Books are typically composed of many pages, bound together and protected by a cover.[1] Modern bound books were preceded by many other written mediums, such as the codex and the scroll. The book publishing process is the series of steps involved in their creation and dissemination.',
      isRead: false,
      isStarred: false,
      isMarked: false, 
      sentAt: 1715593200000,
      isRemoved: true,
      from: 'momo@momo.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e102',
      createdAt: 1551133940500,
      subject: 'Project Update',
      body: 'Please review the latest project updates at your earliest.',
      isRead: true,
      isStarred: false,
      isMarked: false, 
      sentAt: 1715578800000,
      isRemoved: null,
      from: 'project@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e103',
      createdAt: 1655485200000,
      subject: 'Happy Birthday!',
      body: 'Hope you have a fantastic day filled with joy and laughter!',
      isRead: false,
      isStarred: false,
      isMarked: false, 
      sentAt: 1655485200000,
      isRemoved: null,
      from: 'friend@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e104',
      createdAt: 1551133960500,
      subject: 'Scheduled Maintenance',
      body: 'Lawrence called Aaron s Rod the last of my serious English novels - the end of The Rainbow, Women in Love line. Written in the years following the First World War, Aaron s Rod questions many of the accepted social and political institutions of Lawrence s own generation and raises issues still important in our time. Aaron s Rod, completed in',
      isRead: false,
      isStarred: false,
      isMarked: false, 
      sentAt: 1551133960594,
      isRemoved: null,
      from: 'support@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e105',
      createdAt: 1846223400000,
      subject: 'Re: Meeting Rescheduled',
      body: 'The meeting has been rescheduled to next Tuesday.',
      isRead: true,
      isStarred: false,
      isMarked: false, 
      sentAt: 1846224000000,
      isRemoved: null,
      from: 'manager@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e106',
      createdAt: 1551133980500,
      subject: 'Flight Confirmation',
      body: 'Your flight to Tokyo is confirmed for March 15th.Originally written at the turn of the 20th century, this classic story imagines a solar system full of alien life and adventure. A young American woman marries an English Lord and finds herself on the adventure of a lifetime, touring outer space on her honeymoon. Through a series of amazing encounters, they visit the gentle Bird-Folk of Venus',
      isRead: false,
      isStarred: false,
      isMarked: false, 
      sentAt: 1551133980594,
      isRemoved: null,
      from: 'travel@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e107',
      createdAt: 1551133990500,
      subject: 'Subscription Renewal',
      body: 'Your subscription will expire soon. Please renew to continue service.',
      isRead: true,
      isStarred: false,
      isMarked: false, 
      sentAt: 1551133990594,
      isRemoved: null,
      from: 'service@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e108',
      createdAt: 1654916400000,
      subject: 'Security Alert',
      body: 'Unusual activity was detected in your account. Please check your account immediately.',
      isRead: true,
      isStarred: false,
      isMarked: false, 
      sentAt: 1654916400000,
      isRemoved: null,
      from: 'security@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e109',
      createdAt: 1643505600000,
      subject: 'Thank you for your order',
      body: 'We have received your order and it is now being processed.A Bundle of Letters is a humorous story written by an outstanding American novelist and literary critic at the turn of the 20th century. Henry James lived for many years in Europe and not a long time before his death he acquired British citizenship. Most of his stories including A Bundle of Letters touch upon the subject of morality and',
      isRead: false,
      isStarred: true,
      isMarked: false, 
      sentAt: 1643505600000,
      isRemoved: null,
      from: 'orders@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e110',
      createdAt: 1551134020500,
      subject: 'Welcome to the Team!',
      body: 'We are thrilled to have you onboard. Welcome to our team!',
      isRead: true,
      isStarred: true,
      isMarked: false, 
      sentAt: 1551134020594,
      isRemoved: null,
      from: 'hr@appsus.com',
      to: 'user@appsus.com'
    },
    {
      id: 'e111',
      createdAt: 1551133930500,
      subject: 'Miss you!',
      body: 'Would love to catch up sometimes',
      isRead: false,
      isStarred: false,
      isMarked: false, 
      sentAt: 1715593200000,
      isRemoved: null,
      from: 'user@appsus.com' ,
      to: 'momo@momo.com'
    },
    {
      id: 'e112',
      createdAt: 1551133940500,
      subject: 'Project Update',
      body: 'Please review the latest project updates at your earliest.Read the book that inspired the classic coming-of-age film before its back onscreen in select theaters this September! From award-winning German author Michael Ende, The Neverending Story is a classic tale of one boy and the book that magically comes to life. When Bastian happens upon an old book called The',
      isRead: true,
      isStarred: false,
      isMarked: false, 
      sentAt: 1715578800000,
      isRemoved: null,
      from: 'user@appsus.com',
      to: 'project@appsus.com'
    },
    {
      id: 'e113',
      createdAt: 1652950800000,
      subject: 'Happy Birthday!',
      body: 'Hope you have a fantastic day filled with joy and laughter! The classic story from Roald Dahl, about an exceptional young girl with extraordinary powers. Adapted into a Tony Award-winning Broadway musical and a Netflix film! Matilda is a sweet, exceptional young girl, but her parents think shes just a nuisance. She expects school to be different but there she has to face Miss Trunchbull',
      isRead: false,
      isStarred: false,
      isMarked: false, 
      sentAt: 1652950800000,
      isRemoved: null,
      from: 'user@appsus.com',
      to:  'friend@appsus.com'
    },
  ];


  